### ISSUE TITLE
[Feature Request] Add Platte 14 Mensa menu

### ISSUE THREAD

**Issue by kimhanm** [famoser/Mensa#36]
The [Platte 14 Mensa](https://www.mensa.uzh.ch/en/standorte/platte-14.html) is an operation of ZFV-Unternehmungen (just like the other UZH mensas) and is [located](https://www.openstreetmap.org/#map=19/47.37408/8.55266) next to/inside the Institute of Business Administration (IBW).

Their menus are available through [https://www.mensa.uzh.ch/en/menueplaene/platte-14/{$weekday}](https://www.mensa.uzh.ch/en/menueplaene/platte-14/), where weekday in {montag,dienstag,mittwoch,donnerstag,freitag} or through their [menu newsletter](https://zfv.ch/de/forms/menu-newsletter/136) which you can subscribe to.

**Comment by famoser** [comment]
Thank you for the notification! An update has been prepared; and will be published over the next few days.

**Comment by famoser** [comment]
The update was rejected after 9 days; the privacy policy apparently does not fulfill some of the android guidelines. The feedback was unclear; not really sure what to do. I have simplified the privacy policy and re-submitted the update. Sorry to keep you waiting.

**Comment by famoser** [comment]
Apparently missed to press the final "resubmit" button. Now it is again in review.

**Comment by famoser** [comment]
It is still in review:
![image](https://user-images.githubusercontent.com/5077020/193652220-611829d8-da85-4a2c-8865-2eb46250aa11.png)

I do not have any more information about what is going on. As its google, there is also no way to contact some kind of support to ask. [¯\_(ツ)_/¯
