### ISSUE TITLE
Confusing loading state in Battery Saver

### ISSUE THREAD

**Issue by graciouselectric** [famoser/Mensa#43]
Dear developer,

I noticed that, when I enable Battery Saver on Android 8.1, the indeterminate `ProgressBar`s in the app are not properly shown. This is a known problem in Android API level <28, see e.g. [this StackOverflow question](https://stackoverflow.com/questions/35221706/progressbar-disappears-in-battery-saver-mode-android-5-x). Battery Saver disables animations, also on progress bars on these versions. This is quite confusing because the loading state is not properly represented. It is fixed in later Android versions, where progress bars do appear and animate.

Looking at the code, indeterminate progress bars are created here:

```
className='ch.famoser.mensa.services.ProgressCollector', lineNumber=51
```

To fix this issue, one can check [ValueAnimator.areAnimatorsEnabled()](https://developer.android.com/reference/android/animation/ValueAnimator) and provide a different UI element, such as a text label, when animations are disabled.

I also recorded a video, showing the issue in practice:

https://github.com/famoser/Mensa/assets/165037835/3ebfe213-ad8d-4148-8a38-a373e53b0dac

**Comment by famoser** [comment]
Hi, thank you for the detailed report and the suggestions on how to fix it. I‘d be happy to accept a PR improving on this.

**Comment by famoser** [comment]
I am closing this issue, as this is not a high-priority issue from my point of view. I would still accept a PR on this, if you (or someone else) gets around to do this.
